baseurl = "/"
title = "My blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Diego · Torres Arguedas Did it work!?"
    description = "Computer Engineer"
    github = "https://github.com/diegotorrs"
    twitter = "https://twitter.com/XXX"
    email = "diego.torres.arguedas@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"