baseUrl: /
languageCode: en-us
theme: hello-friend
copyright: ''
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # "dark" or "light"
  defaultTheme: dark
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 2

languages:
  en:
    title: Blog
    subtitle: Diego Torres Arguedas
    keywords: ''
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 01-02-2006
    dateFormatList: 01-02-2006
    
    params:
      logo:
        logoText: cd
        logoHomeLink: /
    #   or
    #
    #   path: /img/your-example-logo.svg
    #   alt: Your example logo alt text
    
    menu:
      main:
      - identifier: about
        name: About me
        url: /about