baseurl: "/"
title: "Home"
theme: "ghostwriter"

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2


params:
    mainSections:
        - post
    intro: true
    headline: "Hi, my name is Diego."
    description: "Welcome to my blog. This is space where I share what I learn and what I work on."
    github: "https://github.com/diegotorrs"
    twitter: "https://twitter.com/diego00t"
    email: "diego.torres.arguedas@gmail.com"
    opengraph: true
    shareTwitter: true
    dateFormat: "Mon, Jan 2, 2006"

menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: About
      url: /page/about/
      weight: 0